import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy | Cineboxd",
  description:
    "How Cineboxd handles the data it processes — no ads, no behavioural profiling.",
};

export default function PrivacyPage() {
  return (
    <div className="flex-1">
      <main className="max-w-3xl mx-auto px-4 py-12 space-y-10">
        <div className="space-y-2">
          <h1 className="text-3xl font-semibold tracking-tight">Privacy</h1>
          <p className="text-xs text-muted">Last updated: June 2025</p>
        </div>

        {/* A — Summary */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">Summary</h2>
          <div className="space-y-2 text-muted leading-relaxed text-sm">
            <p>
              Cineboxd is a personal, non-commercial project. It serves no
              advertising, builds no behavioural profiles, and sells no data.
              The sections below describe the limited data processing that does
              occur in order for the service to function.
            </p>
          </div>
        </section>

        {/* B — Data we process */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">Data we process</h2>
          <dl className="space-y-4 text-sm">
            <div>
              <dt className="font-medium text-foreground">Letterboxd usernames</dt>
              <dd className="text-muted leading-relaxed mt-0.5">
                When you enter a Letterboxd username (or several, in Watch
                Together mode), Cineboxd uses it to fetch your public watchlist
                from Letterboxd and compute matches against current screenings.
                Usernames are not stored beyond the duration of a single
                request; the resulting match data is held in your browser
                session only.
              </dd>
            </div>
            <div>
              <dt className="font-medium text-foreground">UK postcode</dt>
              <dd className="text-muted leading-relaxed mt-0.5">
                If you use the &ldquo;near me&rdquo; feature, your postcode is
                stored in your browser&apos;s <code>localStorage</code> and is
                sent to{" "}
                <a
                  href="https://postcodes.io"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline hover:text-foreground"
                >
                  postcodes.io
                </a>{" "}
                (a free, open-source UK geocoding API) to obtain a latitude and
                longitude for distance sorting. The postcode is not sent to
                Cineboxd&apos;s servers; it remains on your device until you
                clear it or your browser storage is cleared.
              </dd>
            </div>
            <div>
              <dt className="font-medium text-foreground">
                Email address and username(s) — weekly alert subscribers only
              </dt>
              <dd className="text-muted leading-relaxed mt-0.5">
                If you opt in to weekly screening alerts, your email address
                and associated Letterboxd username(s) are stored so that alerts
                can be sent to you. Emails are delivered via{" "}
                <a
                  href="https://resend.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline hover:text-foreground"
                >
                  Resend
                </a>
                . Subscription data is held in a JSON file on the server
                (<code>/tmp/subscriptions.json</code> on Vercel, which is
                ephemeral and may be cleared between deploys or cold starts;{" "}
                <code>data/subscriptions.json</code> in local development).
                You can unsubscribe at any time using the link included in
                every alert email.
              </dd>
            </div>
            <div>
              <dt className="font-medium text-foreground">
                Technical and security data
              </dt>
              <dd className="text-muted leading-relaxed mt-0.5">
                IP addresses and user-agent strings are used by an in-memory
                rate limiter (to prevent abuse) and may appear in server logs
                generated by the hosting platform (Vercel). This data is not
                deliberately retained by Cineboxd beyond what the hosting
                provider logs automatically.
              </dd>
            </div>
            <div>
              <dt className="font-medium text-foreground">
                Screening cache (Upstash Redis)
              </dt>
              <dd className="text-muted leading-relaxed mt-0.5">
                When configured, scraped cinema screening data is cached in an
                Upstash Redis database. This cache is intended to contain only
                publicly available screening information and is not designed to
                hold personal data.
              </dd>
            </div>
          </dl>
        </section>

        {/* C — Purposes + lawful bases */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">Purposes and lawful bases</h2>
          <div className="space-y-2 text-sm text-muted leading-relaxed">
            <p>
              <span className="font-medium text-foreground">
                Performance of a service you requested
              </span>{" "}
              — processing your Letterboxd username to fetch your watchlist and
              produce match results is necessary to provide the feature you
              asked for.
            </p>
            <p>
              <span className="font-medium text-foreground">Consent</span> —
              collection of your email address for weekly alerts is based on
              your explicit opt-in. You may withdraw consent at any time by
              unsubscribing.
            </p>
            <p>
              <span className="font-medium text-foreground">
                Legitimate interests
              </span>{" "}
              — rate limiting by IP address and hosting-platform logging are
              carried out to maintain security, prevent abuse, and keep the
              service available.
            </p>
          </div>
        </section>

        {/* D — Retention */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">Retention</h2>
          <div className="space-y-2 text-sm text-muted leading-relaxed">
            <p>
              Username lookups are not stored beyond producing your results.
            </p>
            <p>
              Postcodes remain in your own browser&apos;s{" "}
              <code>localStorage</code> until you clear them or clear your
              browser data.
            </p>
            <p>
              Subscription data (email + username) is retained until you
              unsubscribe. Note that the Vercel deployment stores subscriptions
              in <code>/tmp</code>, which is ephemeral, so in practice records
              may not persist across cold starts or redeployments.
            </p>
            <p>
              Rate-limiter state is held in memory only and is discarded when
              the server process restarts.
            </p>
          </div>
        </section>

        {/* E — Third parties */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">Third-party processors</h2>
          <ul className="space-y-1.5 text-sm text-muted leading-relaxed list-disc list-inside">
            <li>
              <span className="font-medium text-foreground">Vercel</span> —
              hosting and serverless functions; processes request logs including
              IP addresses.
            </li>
            <li>
              <span className="font-medium text-foreground">Upstash</span> —
              Redis-compatible cache for screening data (no personal data
              intended).
            </li>
            <li>
              <span className="font-medium text-foreground">Resend</span> —
              transactional email delivery for alert subscribers.
            </li>
            <li>
              <span className="font-medium text-foreground">TMDB</span> —
              film metadata (posters, ratings, directors); no personal data is
              sent.
            </li>
            <li>
              <span className="font-medium text-foreground">Letterboxd</span>{" "}
              — public watchlists are fetched directly from Letterboxd using
              the username you provide.
            </li>
            <li>
              <span className="font-medium text-foreground">postcodes.io</span>{" "}
              — geocodes the postcode you enter for distance sorting; no
              personal identifiers are attached to the request.
            </li>
          </ul>
        </section>

        {/* F — Cookies / device storage */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">Cookies and device storage</h2>
          <div className="space-y-2 text-sm text-muted leading-relaxed">
            <p>Cineboxd does not use advertising cookies or tracking cookies.</p>
            <p>
              One item of <code>localStorage</code> is written if you use the
              postcode feature (<code>cineboxd_postcode</code>). This is purely
              functional — it persists your postcode preference across visits so
              you do not have to re-enter it — and is never sent to our servers.
            </p>
            <p>
              Because no analytics or advertising cookies are used, no cookie
              consent banner is shown.
            </p>
          </div>
        </section>

        {/* G — Rights + contact */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">Your rights and contact</h2>
          <div className="space-y-2 text-sm text-muted leading-relaxed">
            <p>
              Under UK GDPR you have rights including access to, rectification
              of, and erasure of personal data held about you. Given the minimal
              data processing described above, the most straightforward
              exercising of these rights is:
            </p>
            <ul className="list-disc list-inside space-y-1">
              <li>
                <span className="font-medium text-foreground">
                  Alert subscribers:
                </span>{" "}
                unsubscribe via the link in any alert email to remove your
                subscription record.
              </li>
              <li>
                <span className="font-medium text-foreground">Postcode:</span>{" "}
                clear it using the ✕ button on the site, or clear your
                browser&apos;s <code>localStorage</code> for this domain.
              </li>
              <li>
                <span className="font-medium text-foreground">
                  Any other request:
                </span>{" "}
                use the contact form linked from the{" "}
                <Link href="/about" className="underline hover:text-foreground">
                  About page
                </Link>
                .
              </li>
            </ul>
            <p>
              If you are unsatisfied with how your data is handled you have the
              right to lodge a complaint with the{" "}
              <a
                href="https://ico.org.uk"
                target="_blank"
                rel="noopener noreferrer"
                className="underline hover:text-foreground"
              >
                ICO
              </a>{" "}
              (UK Information Commissioner&apos;s Office).
            </p>
          </div>
        </section>

        <Link
          href="/"
          className="inline-block text-accent hover:underline text-sm"
        >
          &larr; Back to home
        </Link>
      </main>
    </div>
  );
}
